
services:
  elasticsearch:
    image: elasticsearch:8.11.1
    ports:
      - "9200:9200"
    environment:
      - "ES_HEAP_SIZE=2g"

  logstash:
    image: logstash:8.11.1
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d/default.conf
      - ../alumni-api-gateway/alumni-api-gateway/logs:/var/log/logstash
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:8.11.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
